package br.com.jvmsoftware.entities;
// Generated 25/Jun/2015 16:01:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PubEmpresa generated by hbm2java
 */
public class PubEmpresa  implements java.io.Serializable {


     private Integer idEmpresa;
     private PubEstado pubEstado;
     private PubMunicipio pubMunicipio;
     private PubTipoCadastro pubTipoCadastro;
     private Float cnpjEmpresa;
     private String razaoSocial;
     private String fantasia;
     private Float cep;
     private String endereco;
     private Float numero;
     private String bairro;
     private String complemento;
     private Date dataCadastro;
     private boolean ativo;
     private Float telefone;
     private String emailResponsavel;
     private Set<PubConfigEmpresa> pubConfigEmpresas = new HashSet<PubConfigEmpresa>(0);
     private Set<AcsUsuarioSistema> acsUsuarioSistemas = new HashSet<AcsUsuarioSistema>(0);
     private Set<AcsEmpresaSistema> acsEmpresaSistemas = new HashSet<AcsEmpresaSistema>(0);
     private Set<PubUsuario> pubUsuarios = new HashSet<PubUsuario>(0);

    public PubEmpresa() {
    }

	
    public PubEmpresa(PubEstado pubEstado, PubMunicipio pubMunicipio, PubTipoCadastro pubTipoCadastro, String razaoSocial, String fantasia, boolean ativo) {
        this.pubEstado = pubEstado;
        this.pubMunicipio = pubMunicipio;
        this.pubTipoCadastro = pubTipoCadastro;
        this.razaoSocial = razaoSocial;
        this.fantasia = fantasia;
        this.ativo = ativo;
    }
    public PubEmpresa(PubEstado pubEstado, PubMunicipio pubMunicipio, PubTipoCadastro pubTipoCadastro, Float cnpjEmpresa, String razaoSocial, String fantasia, Float cep, String endereco, Float numero, String bairro, String complemento, Date dataCadastro, boolean ativo, Float telefone, String emailResponsavel, Set<PubConfigEmpresa> pubConfigEmpresas, Set<AcsUsuarioSistema> acsUsuarioSistemas, Set<AcsEmpresaSistema> acsEmpresaSistemas, Set<PubUsuario> pubUsuarios) {
       this.pubEstado = pubEstado;
       this.pubMunicipio = pubMunicipio;
       this.pubTipoCadastro = pubTipoCadastro;
       this.cnpjEmpresa = cnpjEmpresa;
       this.razaoSocial = razaoSocial;
       this.fantasia = fantasia;
       this.cep = cep;
       this.endereco = endereco;
       this.numero = numero;
       this.bairro = bairro;
       this.complemento = complemento;
       this.dataCadastro = dataCadastro;
       this.ativo = ativo;
       this.telefone = telefone;
       this.emailResponsavel = emailResponsavel;
       this.pubConfigEmpresas = pubConfigEmpresas;
       this.acsUsuarioSistemas = acsUsuarioSistemas;
       this.acsEmpresaSistemas = acsEmpresaSistemas;
       this.pubUsuarios = pubUsuarios;
    }
   
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public PubEstado getPubEstado() {
        return this.pubEstado;
    }
    
    public void setPubEstado(PubEstado pubEstado) {
        this.pubEstado = pubEstado;
    }
    public PubMunicipio getPubMunicipio() {
        return this.pubMunicipio;
    }
    
    public void setPubMunicipio(PubMunicipio pubMunicipio) {
        this.pubMunicipio = pubMunicipio;
    }
    public PubTipoCadastro getPubTipoCadastro() {
        return this.pubTipoCadastro;
    }
    
    public void setPubTipoCadastro(PubTipoCadastro pubTipoCadastro) {
        this.pubTipoCadastro = pubTipoCadastro;
    }
    public Float getCnpjEmpresa() {
        return this.cnpjEmpresa;
    }
    
    public void setCnpjEmpresa(Float cnpjEmpresa) {
        this.cnpjEmpresa = cnpjEmpresa;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public String getFantasia() {
        return this.fantasia;
    }
    
    public void setFantasia(String fantasia) {
        this.fantasia = fantasia;
    }
    public Float getCep() {
        return this.cep;
    }
    
    public void setCep(Float cep) {
        this.cep = cep;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Float getNumero() {
        return this.numero;
    }
    
    public void setNumero(Float numero) {
        this.numero = numero;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public Float getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Float telefone) {
        this.telefone = telefone;
    }
    public String getEmailResponsavel() {
        return this.emailResponsavel;
    }
    
    public void setEmailResponsavel(String emailResponsavel) {
        this.emailResponsavel = emailResponsavel;
    }
    public Set<PubConfigEmpresa> getPubConfigEmpresas() {
        return this.pubConfigEmpresas;
    }
    
    public void setPubConfigEmpresas(Set<PubConfigEmpresa> pubConfigEmpresas) {
        this.pubConfigEmpresas = pubConfigEmpresas;
    }
    public Set<AcsUsuarioSistema> getAcsUsuarioSistemas() {
        return this.acsUsuarioSistemas;
    }
    
    public void setAcsUsuarioSistemas(Set<AcsUsuarioSistema> acsUsuarioSistemas) {
        this.acsUsuarioSistemas = acsUsuarioSistemas;
    }
    public Set<AcsEmpresaSistema> getAcsEmpresaSistemas() {
        return this.acsEmpresaSistemas;
    }
    
    public void setAcsEmpresaSistemas(Set<AcsEmpresaSistema> acsEmpresaSistemas) {
        this.acsEmpresaSistemas = acsEmpresaSistemas;
    }
    public Set<PubUsuario> getPubUsuarios() {
        return this.pubUsuarios;
    }
    
    public void setPubUsuarios(Set<PubUsuario> pubUsuarios) {
        this.pubUsuarios = pubUsuarios;
    }




}


