package br.com.jvmsoftware.entities;
// Generated 12/Jul/2015 22:01:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PubFuncionalidade generated by hbm2java
 */
public class PubFuncionalidade  implements java.io.Serializable {


     private Integer idFuncionalidade;
     private String descricaoFuncionalidade;
     private int sistema;
     private Set<SupSolicitacao> supSolicitacaos = new HashSet<SupSolicitacao>(0);
     private Set<WflWorkflow> wflWorkflows = new HashSet<WflWorkflow>(0);

    public PubFuncionalidade() {
    }

	
    public PubFuncionalidade(String descricaoFuncionalidade, int sistema) {
        this.descricaoFuncionalidade = descricaoFuncionalidade;
        this.sistema = sistema;
    }
    public PubFuncionalidade(String descricaoFuncionalidade, int sistema, Set<SupSolicitacao> supSolicitacaos, Set<WflWorkflow> wflWorkflows) {
       this.descricaoFuncionalidade = descricaoFuncionalidade;
       this.sistema = sistema;
       this.supSolicitacaos = supSolicitacaos;
       this.wflWorkflows = wflWorkflows;
    }
   
    public Integer getIdFuncionalidade() {
        return this.idFuncionalidade;
    }
    
    public void setIdFuncionalidade(Integer idFuncionalidade) {
        this.idFuncionalidade = idFuncionalidade;
    }
    public String getDescricaoFuncionalidade() {
        return this.descricaoFuncionalidade;
    }
    
    public void setDescricaoFuncionalidade(String descricaoFuncionalidade) {
        this.descricaoFuncionalidade = descricaoFuncionalidade;
    }
    public int getSistema() {
        return this.sistema;
    }
    
    public void setSistema(int sistema) {
        this.sistema = sistema;
    }
    public Set<SupSolicitacao> getSupSolicitacaos() {
        return this.supSolicitacaos;
    }
    
    public void setSupSolicitacaos(Set<SupSolicitacao> supSolicitacaos) {
        this.supSolicitacaos = supSolicitacaos;
    }
    public Set<WflWorkflow> getWflWorkflows() {
        return this.wflWorkflows;
    }
    
    public void setWflWorkflows(Set<WflWorkflow> wflWorkflows) {
        this.wflWorkflows = wflWorkflows;
    }




}


